

name: cli release

on:
  release:
    types: [ published ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, darwin ]  # Target systems,
        goarch: [ "386", amd64, arm64 ]   # with their architecture.
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.18
          binary_name: "feltna"
          extra_files: LICENSE  # Additional files to include with the binaries.
